### PR TITLE
Added PHP 7.0 and 7.1 and did a lot of cleanup

### PR DESCRIPTION
**Pull request by dimitri-koenig**
Only check being done is php lint, therefore: cleanup!
Or did I miss something?

### CODE REVIEW

**Comment by garbast** [comment]
Sorry, but i dont think i like this patch.

The composer stuff should not be dropped to enable unit tests in future. So from my understanding all the removed part should stay.

The next part i realy dont see to make it into the master is the branches only part. This tests should only be run on merge into master, tag creation (because of pre release testing and releasing) and on testing_* branches. By this pushes to development branches do not trigger travis runs everytime.

Only part i can see to take over is the php: 7.0 and 7.1 parts. But from what i understood the include part does already take these versions into account.

**Comment by dimitri-koenig** [comment]
Let me explain my thoughts in more detail:

* WHEN someday unit tests will enter the field THEN it totally makes sense to think about extending this travis config. But then a composer way may not be the best solution because dependency management and forced versions thought not officially supported is not (easy) possible with composer.
* Running tests on every commit is cheap. Therefore it does not make sense at all to only let them run on certain branches.

**Comment by garbast** [comment]
Ok i end the discussion here. For this repository this will not make it in. You can configure your repository how ever you like. But for now the settings are set. There is no need to change them because by now no other developer is working on it.
It's totaly fine to have your own set of configuration for your fork but i dont see any improvement that requires a pull request which only consists of throwing stuff away.

**Comment by dimitri-koenig** [comment]
No offense ;-)
It was just a suggestion...

**Pull request closed without merging**
